### ISSUE TITLE
[Question] Full Accounting in OCB 15.0 or 16.0

### ISSUE THREAD

**Issue by kamarya** [OCA/community-data-files#159]
There are so many repositories under OCA organisation. Which repos. do I need to install from OCA to have full accounting support in OCB 15.0 or 16.0 ?

**Comment by youring** [comment]
AFAIK, there is not an "All-in-one Accounting" app in OCA repositories. You have to install specific modules available according to your needs. If not available in specific version, you can check opening pull requests or create pull request to migrate or contribute your own solution.
For the record, current accounting related repos:
https://github.com/OCA/account-reconcile
https://github.com/OCA/account-payment
https://github.com/OCA/account-invoicing
https://github.com/OCA/account-invoice-reporting
https://github.com/OCA/account-fiscal-rule
https://github.com/OCA/account-financial-tools
https://github.com/OCA/account-financial-reporting
https://github.com/OCA/account-consolidation
https://github.com/OCA/account-closing
https://github.com/OCA/account-analytic
https://github.com/OCA/account-budgeting
https://github.com/OCA/mis-builder
https://github.com/OCA/mis-builder-contrib

And maybe some in your country's localization repo.

**Comment by pedrobaeza** [comment]
Closing as no OCB issue.
