### ISSUE TITLE
Wanting to contribute!

### ISSUE THREAD

**Issue by jordillinares** [OCA/community-data-files#4]
Hi folks!

I'd like to contribute to the development of the NACE modules. I didn't know the existence of this project, so I developed [a module of my own](https://github.com/jordillinares/addons/tree/master/l10n_es_cnae_2009) with spanish CNAE version. This module sets an entity for NACE records (only spanish version), and relates it to leads and partners through many2many_tags widgets on their respective forms. It also writes the NACE codes of a given lead to the partner created when lead is escalated to opportunity.

I thought I'd better somehow refactor and integrate my work into this project. If you agree, let me know how I can help.

**Comment by clonedagain** [comment]
@jordillinares I'm glad someone shows interest in this.
@pedrobaeza will surely be able to help you with this, as he very involved in the Spanish l10n.

At the moment the best I can tell you is to have a look at how I've implemented the French NAF codes to reuse the NACE codes.
In France you can have only one NAF code per company, so I added a many2one for the main activity, and users can still add additionnal activities as partner categories.
The source is here:
- v7 here https://github.com/OCA/community-data-files/tree/7.0/l10n_fr_naf_ape
- v8 (moved to l10n-france, merge pending) https://github.com/OCA/l10n-france/pull/3/files

**Comment by pedrobaeza** [comment]
Yeah, I have been already in contact with him :wink:

**Comment by clonedagain** [comment]
OK then don't hesitate to ping me on a PR if you want further opinions/advice from me.

**Comment by hbrunn** [comment]
this one seems to be discussed out
