### ISSUE TITLE
base_currency_iso_4217 data errors

### ISSUE THREAD

**Issue by levkar** [OCA/community-data-files#44]
Some duplicate data in res_currency_data.xml (for example base.EUR)

Some have different names with same id (for example base.TRY) Turkish Lira & New Turkish Lira. 

Shouldn't it be based on https://www.iso.org/iso-4217-currency-codes.html ?

Very nice and necessary  module indeed! Thanks!

@jbeficent

**Comment by JordiBForgeFlow** [comment]
Thanks Levent,

Can you propose a PR?

**Comment by levkar** [comment]
I will do it once i print, sign the CLA and send it to OCA.

**Comment by pedrobaeza** [comment]
@levkar you can sign it digitally if you prefer

**Comment by levkar** [comment]
@pedrobaeza

How? It is not mentioned in OCA page:

https://odoo-community.org/page/cla

**Comment by pedrobaeza** [comment]
You're right: it's not mentioned in the page. I'll update it, but a digital sign on the PDF is also valid.

**Comment by levkar** [comment]
this is fixed
