### ISSUE TITLE
Improvements for NACE addons

### ISSUE THREAD

**Issue by antespi** [OCA/community-data-files#5]
We have just developt an addon for downloading NACE items in proper languages and associating them to partner via a custom field, instead of category. More details in https://github.com/OCA/partner-contact/pull/106. Main new features are:
- Use custom partner fields (main_nace/many2one and secondary_naces/many2many), don't use res.partner.category. Reasons:
  - NACE texts are so long
  - NACE items have rich descriptions to indicate user when used them.
- Downloads NACE items from RAMON online service, and translates them in all available languages (all languages of European Community countries) through a wizard.
- Filter partners by main NACE activity
- Group partner by main NACE activity 

As @clonedagain comments:

> The existing NACE module uses partner categories because several community modules worked this way.
> If you think it's wrong please just make a proposal to change the existing module.
> I for one have no preferences. If others agree with you I'd not block, as long as migration scripts are provided.

We do not have enought resources to improve OCA/community-data-files/l10n_eu_nace addon and we have already partner_nace addon in production in one customer. But, we moved this PR to our public repo, https://github.com/Antiun/antiun-odoo-addons/commit/59b062c1296c8b2d41ec3b7d7ec0e0e206e27761, in order to allow anyone to do pending work:
- Merge new features (Antiun/antiun-odoo-addons/partner_nace)
- Provide migration scripts from current version (l10n_eu_nace) to new implementation

References:
- https://github.com/OCA/partner-contact/pull/106
- https://github.com/Antiun/antiun-odoo-addons/commit/59b062c1296c8b2d41ec3b7d7ec0e0e206e27761
- https://github.com/OCA/community-data-files/issues/4
- https://github.com/jordillinares/addons/tree/master/l10n_es_cnae_2009
- https://github.com/OCA/l10n-france/pull/3
- https://github.com/OCA/community-data-files/pull/3

**Comment by antespi** [comment]
FYI @jordillinares and @pedrobaeza

**Comment by hbrunn** [comment]
is this one still relevant or can we close it?

**Comment by LeartS** [comment]
As someone who has to implement the NACE classification on an Odoo instance for a customer; I would say at least parts of the changes proposed here are needed; the module as it is now does not provide a great user experience IMO. I would leave the issue open so others like me can quickly find it and use it as a place for discussion/improvements.

I am probably going to implement something similar to what has been discussed in the linked partner-contact PR: leave the NACE fields as a many2many to res.partner.category, add a primary activity many2one field and use that to create a filter and groupby on partners. Probably add a boolean field on the res.partner.category model to separate NACE categories from other categories.

What do you think?

**Comment by pedrobaeza** [comment]
I agree. Check https://github.com/Antiun/antiun-odoo-addons/tree/8.0/partner_nace for an implementation from the ground.

The only problem I see with using res.partner.category is to have these labels mixed with the rest of the possible labels to use, so I still wonder if we should switch this module directly.

**Comment by pedrobaeza** [comment]
@LeartS any news about this?
